version: 2.1
orbs:
    node: circleci/node@4.0
jobs:
    deploy:
        machine:
            image: ubuntu-2004:202010-01
        steps:
            # Do something to deploy project
            - run:
                  name: Deployment
                  command: echo 'This project has been deployed.'

workflows:
    my-pipeline:
        jobs:
            - node/test
            - deploy:
                  requires:
                      - node/test
                  filters:
                      branches:
                          only:
                              - master
