version: 2.1
orbs:
    node: circleci/node@4.7.0

jobs:
    test:
        docker:
            - image: cimg/node:15.1

        steps:
            - checkout
            - node/install-packages
            - run:
                  name: Run test
                  command: npm run test

    deploy:
        docker:
            - image: cimg/node:15.1
        steps:
            # Do something to deploy project
            - run:
                  name: Deployment
                  command: echo 'This project has been deployed.'

workflows:
    demo-ci:
        jobs:
            - test
            - deploy:
                  requires:
                      - test
                  filters:
                      branches:
                          only:
                              - master
