version: 2.1
orbs:
    node: circleci/node@4.0
jobs:
    deploy:
        machine:
            image: ubuntu-2004:202010-01
        steps:
            # Do something to deploy project
            - run:
                  name: Deployment
                  command: echo 'This project has been deployed.'
    install:
        steps:
            - run:
              
              if [ -e yarn.lock ]; then
              yarn install --pure-lockfile
              elif [ -e package-lock.json ]; then
              npm ci
              else
              npm i
              fi

workflows:
    my-pipeline:
        jobs:
            - install:
            - node/test
            - deploy:
                  requires:
                      - node/test
                  filters:
                      branches:
                          only:
                              - master
