version: 2.1
orbs:
    node: circleci/node@4.7
jobs:
    deploy:
        machine:
            image: ubuntu-2004:202010-01
        steps:
            # Do something to deploy project
            - run:
                  name: Deployment
                  command: echo 'This project has been deployed.'
    install:
        steps:
            - run:
              name: install
              command: yarn install --pure-lockfile

workflows:
    my-pipeline:
        jobs:
            - install
            - node/test:
                  requires:
                      - install
            - deploy:
                  requires:
                      - node/test
                  filters:
                      branches:
                          only:
                              - master
