# version: 2.1
# orbs:
#     node: circleci/node@4.7
# commands:
#     setup-node-and-yarn-install-with-cache:
#         steps:
#             - node/install:
#                   install-yarn: true
#                   node-version: latest
#             - node/install-packages:
#                   pkg-manager: yarn
#                   cache-key: yarn.lock
# jobs:
#     deploy:
#         # machine:
#         #     image: ubuntu-2004:202010-01
#         executor:
#             name: node/default
#         steps:
#             # Do something to deploy project
#             - run:
#                   name: Deployment
#                   command: echo 'This project has been deployed.'
#     lint-and-test:
#         executor:
#             name: node/default
#         steps:
#             - checkout
#             - setup-node-and-yarn-install-with-cache
#             - run:
#                   name: Lint
#                   command: npm run lint
#             - run:
#                   name: Check types
#                   command: npm run check-types
#             - run:
#                   name: Run tests
#                   command: npm run test
# workflows:
#     demo-ci:
#         jobs:
#             - lint-and-test
#             - deploy:
#                   requires:
#                       - lint-and-test
#                   filters:
#                       branches:
#                           only:
#                               - master
version: 2.1
orbs:
    node: circleci/node@4.7.0

jobs:
    test:
        docker:
            - image: cimg/node:15.1

        steps:
            - checkout
            - node/install-packages
            - run:
                  name: Run test
                  command: npm run test
    
     deploy:
        docker:
            - image: cimg/node:15.1

        steps:
            # Do something to deploy project
            - run:
                  name: Deployment
                  command: echo 'This project has been deployed.'

workflows:
    # Below is the definition of your workflow.
    # Inside the workflow, you provide the jobs you want to run, e.g this workflow runs the build-and-test job above.
    # CircleCI will run this workflow on every commit.
    # For more details on extending your workflow, see the configuration docs: https://circleci.com/docs/2.0/configuration-reference/#workflows
    sample:
        jobs:
            - test
            - node/test
            - deploy:
                requires:
                    - node/test
                filters:
                    branches:
                        only:
                            - master
